[build]
  publish = "D:\Sites Dev\jogo da cobrinha" # Altere para o seu diretório de build
  functions = "functions"

[[redirects]]
  from = "/.functions/*"
  to = "/.functions/:splat"
  status = 200
